import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "../Components/Container";
import { Title } from "../Components/Title";
import { MoviesList } from "../Components/MoviesList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Title title="Show top 500 movies in TMDB" />
        <MoviesList />
      </Container>
    </>
  );
};

export default Home;
